### ISSUE TITLE
Support SVG markers

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis-api#11]
Test with MAKI icons: https://www.mapbox.com/maki/

https://groups.google.com/forum/#!topic/leaflet-js/GSisdUm5rEc
https://github.com/hiasinho/Leaflet.vector-markers

**Comment by jason-p-pickering** [comment]
I did an initial test with the new client with a new set of SVG icons and it seems to work out of the box really. 
![selection_474](https://cloud.githubusercontent.com/assets/2968061/13283896/eb650ae2-daf0-11e5-861d-9e88371049cd.png)

The feature I would like to see however would be the ability to use the base SVG object, specify the fill and possibly stroke color, and size. In the meantime however, I will go ahead and rework the PNGs I added yesterday to be SVG instead?

**Comment by turban** [comment]
SVG markers is supported out of the box. A marker generator is a separate issue. Could be based on makizushi: https://github.com/mapbox/makizushi
